// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// ActiveIssuesForCompletionResponse is returned by ActiveIssuesForCompletion on success.
type ActiveIssuesForCompletionResponse struct {
	// The currently authenticated user.
	Viewer *ActiveIssuesForCompletionViewerUser `json:"viewer"`
}

// GetViewer returns ActiveIssuesForCompletionResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionResponse) GetViewer() *ActiveIssuesForCompletionViewerUser {
	return v.Viewer
}

// ActiveIssuesForCompletionViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ActiveIssuesForCompletionViewerUser struct {
	// Issues assigned to the user.
	AssignedIssues *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns ActiveIssuesForCompletionViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionViewerUser) GetAssignedIssues() *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection struct {
	Nodes []*ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection) GetNodes() []*ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
}

// GetIdentifier returns ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetIssueIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type GetIssueIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
	// The issue's description in markdown format.
	Description *string `json:"description"`
	// Issue URL.
	Url string `json:"url"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
	Priority float64 `json:"priority"`
	// The estimate of the complexity of the issue..
	Estimate *float64 `json:"estimate"`
	// The date at which the issue is due.
	DueDate *string `json:"dueDate"`
	// The time at which the entity was created.
	CreatedAt string `json:"createdAt"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
	// Suggested branch name for the issue.
	BranchName string `json:"branchName"`
	// The workflow state that the issue is associated with.
	State *GetIssueIssueStateWorkflowState `json:"state"`
	// The user to whom the issue is assigned to.
	Assignee *GetIssueIssueAssigneeUser `json:"assignee"`
	// The team that the issue is associated with.
	Team *GetIssueIssueTeam `json:"team"`
	// The project that the issue is associated with.
	Project *GetIssueIssueProject `json:"project"`
	// Labels associated with this issue.
	Labels *GetIssueIssueLabelsIssueLabelConnection `json:"labels"`
	// The parent of the issue.
	Parent *GetIssueIssueParentIssue `json:"parent"`
}

// GetId returns GetIssueIssue.Id, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetId() string { return v.Id }

// GetIdentifier returns GetIssueIssue.Identifier, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetIdentifier() string { return v.Identifier }

// GetTitle returns GetIssueIssue.Title, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetTitle() string { return v.Title }

// GetDescription returns GetIssueIssue.Description, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetDescription() *string { return v.Description }

// GetUrl returns GetIssueIssue.Url, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetUrl() string { return v.Url }

// GetPriority returns GetIssueIssue.Priority, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetPriority() float64 { return v.Priority }

// GetEstimate returns GetIssueIssue.Estimate, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetEstimate() *float64 { return v.Estimate }

// GetDueDate returns GetIssueIssue.DueDate, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetDueDate() *string { return v.DueDate }

// GetCreatedAt returns GetIssueIssue.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns GetIssueIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetUpdatedAt() string { return v.UpdatedAt }

// GetBranchName returns GetIssueIssue.BranchName, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetBranchName() string { return v.BranchName }

// GetState returns GetIssueIssue.State, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetState() *GetIssueIssueStateWorkflowState { return v.State }

// GetAssignee returns GetIssueIssue.Assignee, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetAssignee() *GetIssueIssueAssigneeUser { return v.Assignee }

// GetTeam returns GetIssueIssue.Team, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetTeam() *GetIssueIssueTeam { return v.Team }

// GetProject returns GetIssueIssue.Project, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetProject() *GetIssueIssueProject { return v.Project }

// GetLabels returns GetIssueIssue.Labels, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetLabels() *GetIssueIssueLabelsIssueLabelConnection { return v.Labels }

// GetParent returns GetIssueIssue.Parent, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetParent() *GetIssueIssueParentIssue { return v.Parent }

// GetIssueIssueAssigneeUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type GetIssueIssueAssigneeUser struct {
	// The user's full name.
	Name string `json:"name"`
	// The user's email address.
	Email string `json:"email"`
}

// GetName returns GetIssueIssueAssigneeUser.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueAssigneeUser) GetName() string { return v.Name }

// GetEmail returns GetIssueIssueAssigneeUser.Email, and is useful for accessing the field via an interface.
func (v *GetIssueIssueAssigneeUser) GetEmail() string { return v.Email }

// GetIssueIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type GetIssueIssueLabelsIssueLabelConnection struct {
	Nodes []*GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns GetIssueIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetIssueIssueLabelsIssueLabelConnection) GetNodes() []*GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues.
type GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string { return v.Name }

// GetIssueIssueParentIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type GetIssueIssueParentIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
}

// GetIdentifier returns GetIssueIssueParentIssue.Identifier, and is useful for accessing the field via an interface.
func (v *GetIssueIssueParentIssue) GetIdentifier() string { return v.Identifier }

// GetTitle returns GetIssueIssueParentIssue.Title, and is useful for accessing the field via an interface.
func (v *GetIssueIssueParentIssue) GetTitle() string { return v.Title }

// GetIssueIssueProject includes the requested fields of the GraphQL type Project.
// The GraphQL type's documentation follows.
//
// A project.
type GetIssueIssueProject struct {
	// The project's name.
	Name string `json:"name"`
}

// GetName returns GetIssueIssueProject.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueProject) GetName() string { return v.Name }

// GetIssueIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team workflow.
type GetIssueIssueStateWorkflowState struct {
	// The state's name.
	Name string `json:"name"`
	// The type of the state. One of "triage", "backlog", "unstarted", "started", "completed", "canceled".
	Type string `json:"type"`
}

// GetName returns GetIssueIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueStateWorkflowState) GetName() string { return v.Name }

// GetType returns GetIssueIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *GetIssueIssueStateWorkflowState) GetType() string { return v.Type }

// GetIssueIssueTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// An organizational unit that contains issues.
type GetIssueIssueTeam struct {
	// The team's name.
	Name string `json:"name"`
	// The team's unique key. The key is used in URLs.
	Key string `json:"key"`
}

// GetName returns GetIssueIssueTeam.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueTeam) GetName() string { return v.Name }

// GetKey returns GetIssueIssueTeam.Key, and is useful for accessing the field via an interface.
func (v *GetIssueIssueTeam) GetKey() string { return v.Key }

// GetIssueResponse is returned by GetIssue on success.
type GetIssueResponse struct {
	// One specific issue.
	Issue *GetIssueIssue `json:"issue"`
}

// GetIssue returns GetIssueResponse.Issue, and is useful for accessing the field via an interface.
func (v *GetIssueResponse) GetIssue() *GetIssueIssue { return v.Issue }

// ListMyActiveIssuesResponse is returned by ListMyActiveIssues on success.
type ListMyActiveIssuesResponse struct {
	// The currently authenticated user.
	Viewer *ListMyActiveIssuesViewerUser `json:"viewer"`
}

// GetViewer returns ListMyActiveIssuesResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesResponse) GetViewer() *ListMyActiveIssuesViewerUser { return v.Viewer }

// ListMyActiveIssuesViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ListMyActiveIssuesViewerUser struct {
	// Issues assigned to the user.
	AssignedIssues *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns ListMyActiveIssuesViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUser) GetAssignedIssues() *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection struct {
	Nodes    []*ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
	PageInfo *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo     `json:"pageInfo"`
}

// GetNodes returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection) GetNodes() []*ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GetPageInfo returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection) GetPageInfo() *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
	// The workflow state that the issue is associated with.
	State *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState `json:"state"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
	Priority float64 `json:"priority"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
	// Labels associated with this issue.
	Labels *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection `json:"labels"`
}

// GetId returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetId() string {
	return v.Id
}

// GetIdentifier returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetState returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetState() *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetPriority returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Priority, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetPriority() float64 {
	return v.Priority
}

// GetUpdatedAt returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetLabels returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Labels, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetLabels() *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection {
	return v.Labels
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection struct {
	Nodes []*ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection) GetNodes() []*ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string {
	return v.Name
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team workflow.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState struct {
	// The state's name.
	Name string `json:"name"`
	// The type of the state. One of "triage", "backlog", "unstarted", "started", "completed", "canceled".
	Type string `json:"type"`
}

// GetName returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetType returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetType() string {
	return v.Type
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo) GetEndCursor() *string {
	return v.EndCursor
}

// ListMyAllIssuesResponse is returned by ListMyAllIssues on success.
type ListMyAllIssuesResponse struct {
	// The currently authenticated user.
	Viewer *ListMyAllIssuesViewerUser `json:"viewer"`
}

// GetViewer returns ListMyAllIssuesResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesResponse) GetViewer() *ListMyAllIssuesViewerUser { return v.Viewer }

// ListMyAllIssuesViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ListMyAllIssuesViewerUser struct {
	// Issues assigned to the user.
	AssignedIssues *ListMyAllIssuesViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns ListMyAllIssuesViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUser) GetAssignedIssues() *ListMyAllIssuesViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnection struct {
	Nodes    []*ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
	PageInfo *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo     `json:"pageInfo"`
}

// GetNodes returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnection) GetNodes() []*ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GetPageInfo returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnection) GetPageInfo() *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
	// The workflow state that the issue is associated with.
	State *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState `json:"state"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
	Priority float64 `json:"priority"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
	// Labels associated with this issue.
	Labels *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection `json:"labels"`
}

// GetId returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetId() string {
	return v.Id
}

// GetIdentifier returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetState returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetState() *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetPriority returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Priority, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetPriority() float64 {
	return v.Priority
}

// GetUpdatedAt returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetLabels returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Labels, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetLabels() *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection {
	return v.Labels
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection struct {
	Nodes []*ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection) GetNodes() []*ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string {
	return v.Name
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team workflow.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState struct {
	// The state's name.
	Name string `json:"name"`
	// The type of the state. One of "triage", "backlog", "unstarted", "started", "completed", "canceled".
	Type string `json:"type"`
}

// GetName returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetType returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetType() string {
	return v.Type
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo) GetEndCursor() *string {
	return v.EndCursor
}

// ViewerResponse is returned by Viewer on success.
type ViewerResponse struct {
	// The currently authenticated user.
	Viewer *ViewerViewerUser `json:"viewer"`
}

// GetViewer returns ViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ViewerResponse) GetViewer() *ViewerViewerUser { return v.Viewer }

// ViewerViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ViewerViewerUser struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The user's full name.
	Name string `json:"name"`
	// The user's email address.
	Email string `json:"email"`
}

// GetId returns ViewerViewerUser.Id, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetId() string { return v.Id }

// GetName returns ViewerViewerUser.Name, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetName() string { return v.Name }

// GetEmail returns ViewerViewerUser.Email, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetEmail() string { return v.Email }

// __ActiveIssuesForCompletionInput is used internally by genqlient
type __ActiveIssuesForCompletionInput struct {
	First int `json:"first"`
}

// GetFirst returns __ActiveIssuesForCompletionInput.First, and is useful for accessing the field via an interface.
func (v *__ActiveIssuesForCompletionInput) GetFirst() int { return v.First }

// __GetIssueInput is used internally by genqlient
type __GetIssueInput struct {
	Id string `json:"id"`
}

// GetId returns __GetIssueInput.Id, and is useful for accessing the field via an interface.
func (v *__GetIssueInput) GetId() string { return v.Id }

// __ListMyActiveIssuesInput is used internally by genqlient
type __ListMyActiveIssuesInput struct {
	First int     `json:"first"`
	After *string `json:"after"`
}

// GetFirst returns __ListMyActiveIssuesInput.First, and is useful for accessing the field via an interface.
func (v *__ListMyActiveIssuesInput) GetFirst() int { return v.First }

// GetAfter returns __ListMyActiveIssuesInput.After, and is useful for accessing the field via an interface.
func (v *__ListMyActiveIssuesInput) GetAfter() *string { return v.After }

// __ListMyAllIssuesInput is used internally by genqlient
type __ListMyAllIssuesInput struct {
	First int     `json:"first"`
	After *string `json:"after"`
}

// GetFirst returns __ListMyAllIssuesInput.First, and is useful for accessing the field via an interface.
func (v *__ListMyAllIssuesInput) GetFirst() int { return v.First }

// GetAfter returns __ListMyAllIssuesInput.After, and is useful for accessing the field via an interface.
func (v *__ListMyAllIssuesInput) GetAfter() *string { return v.After }

// The query or mutation executed by ActiveIssuesForCompletion.
const ActiveIssuesForCompletion_Operation = `
query ActiveIssuesForCompletion ($first: Int!) {
	viewer {
		assignedIssues(first: $first, filter: {state:{type:{nin:["completed","canceled"]}}}) {
			nodes {
				identifier
				title
			}
		}
	}
}
`

func ActiveIssuesForCompletion(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
) (*ActiveIssuesForCompletionResponse, error) {
	req_ := &graphql.Request{
		OpName: "ActiveIssuesForCompletion",
		Query:  ActiveIssuesForCompletion_Operation,
		Variables: &__ActiveIssuesForCompletionInput{
			First: first,
		},
	}
	var err_ error

	var data_ ActiveIssuesForCompletionResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by GetIssue.
const GetIssue_Operation = `
query GetIssue ($id: String!) {
	issue(id: $id) {
		id
		identifier
		title
		description
		url
		priority
		estimate
		dueDate
		createdAt
		updatedAt
		branchName
		state {
			name
			type
		}
		assignee {
			name
			email
		}
		team {
			name
			key
		}
		project {
			name
		}
		labels {
			nodes {
				name
			}
		}
		parent {
			identifier
			title
		}
	}
}
`

func GetIssue(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (*GetIssueResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetIssue",
		Query:  GetIssue_Operation,
		Variables: &__GetIssueInput{
			Id: id,
		},
	}
	var err_ error

	var data_ GetIssueResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListMyActiveIssues.
const ListMyActiveIssues_Operation = `
query ListMyActiveIssues ($first: Int!, $after: String) {
	viewer {
		assignedIssues(first: $first, after: $after, filter: {state:{type:{nin:["completed","canceled"]}}}) {
			nodes {
				id
				identifier
				title
				state {
					name
					type
				}
				priority
				updatedAt
				labels {
					nodes {
						name
					}
				}
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}
`

func ListMyActiveIssues(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after *string,
) (*ListMyActiveIssuesResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListMyActiveIssues",
		Query:  ListMyActiveIssues_Operation,
		Variables: &__ListMyActiveIssuesInput{
			First: first,
			After: after,
		},
	}
	var err_ error

	var data_ ListMyActiveIssuesResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListMyAllIssues.
const ListMyAllIssues_Operation = `
query ListMyAllIssues ($first: Int!, $after: String) {
	viewer {
		assignedIssues(first: $first, after: $after) {
			nodes {
				id
				identifier
				title
				state {
					name
					type
				}
				priority
				updatedAt
				labels {
					nodes {
						name
					}
				}
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}
`

func ListMyAllIssues(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after *string,
) (*ListMyAllIssuesResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListMyAllIssues",
		Query:  ListMyAllIssues_Operation,
		Variables: &__ListMyAllIssuesInput{
			First: first,
			After: after,
		},
	}
	var err_ error

	var data_ ListMyAllIssuesResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by Viewer.
const Viewer_Operation = `
query Viewer {
	viewer {
		id
		name
		email
	}
}
`

func Viewer(
	ctx_ context.Context,
	client_ graphql.Client,
) (*ViewerResponse, error) {
	req_ := &graphql.Request{
		OpName: "Viewer",
		Query:  Viewer_Operation,
	}
	var err_ error

	var data_ ViewerResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
