// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// ActiveIssuesForCompletionResponse is returned by ActiveIssuesForCompletion on success.
type ActiveIssuesForCompletionResponse struct {
	// The currently authenticated user.
	Viewer *ActiveIssuesForCompletionViewerUser `json:"viewer"`
}

// GetViewer returns ActiveIssuesForCompletionResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionResponse) GetViewer() *ActiveIssuesForCompletionViewerUser {
	return v.Viewer
}

// ActiveIssuesForCompletionViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ActiveIssuesForCompletionViewerUser struct {
	// Issues assigned to the user.
	AssignedIssues *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns ActiveIssuesForCompletionViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionViewerUser) GetAssignedIssues() *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection struct {
	Nodes []*ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnection) GetNodes() []*ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
}

// GetIdentifier returns ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *ActiveIssuesForCompletionViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetIssueIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type GetIssueIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
	// The issue's description in markdown format.
	Description *string `json:"description"`
	// Issue URL.
	Url string `json:"url"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
	Priority float64 `json:"priority"`
	// The estimate of the complexity of the issue..
	Estimate *float64 `json:"estimate"`
	// The date at which the issue is due.
	DueDate *string `json:"dueDate"`
	// The time at which the entity was created.
	CreatedAt string `json:"createdAt"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
	// Suggested branch name for the issue.
	BranchName string `json:"branchName"`
	// The workflow state that the issue is associated with.
	State *GetIssueIssueStateWorkflowState `json:"state"`
	// The user to whom the issue is assigned to.
	Assignee *GetIssueIssueAssigneeUser `json:"assignee"`
	// The team that the issue is associated with.
	Team *GetIssueIssueTeam `json:"team"`
	// The project that the issue is associated with.
	Project *GetIssueIssueProject `json:"project"`
	// Labels associated with this issue.
	Labels *GetIssueIssueLabelsIssueLabelConnection `json:"labels"`
	// The parent of the issue.
	Parent *GetIssueIssueParentIssue `json:"parent"`
}

// GetId returns GetIssueIssue.Id, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetId() string { return v.Id }

// GetIdentifier returns GetIssueIssue.Identifier, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetIdentifier() string { return v.Identifier }

// GetTitle returns GetIssueIssue.Title, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetTitle() string { return v.Title }

// GetDescription returns GetIssueIssue.Description, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetDescription() *string { return v.Description }

// GetUrl returns GetIssueIssue.Url, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetUrl() string { return v.Url }

// GetPriority returns GetIssueIssue.Priority, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetPriority() float64 { return v.Priority }

// GetEstimate returns GetIssueIssue.Estimate, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetEstimate() *float64 { return v.Estimate }

// GetDueDate returns GetIssueIssue.DueDate, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetDueDate() *string { return v.DueDate }

// GetCreatedAt returns GetIssueIssue.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns GetIssueIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetUpdatedAt() string { return v.UpdatedAt }

// GetBranchName returns GetIssueIssue.BranchName, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetBranchName() string { return v.BranchName }

// GetState returns GetIssueIssue.State, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetState() *GetIssueIssueStateWorkflowState { return v.State }

// GetAssignee returns GetIssueIssue.Assignee, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetAssignee() *GetIssueIssueAssigneeUser { return v.Assignee }

// GetTeam returns GetIssueIssue.Team, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetTeam() *GetIssueIssueTeam { return v.Team }

// GetProject returns GetIssueIssue.Project, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetProject() *GetIssueIssueProject { return v.Project }

// GetLabels returns GetIssueIssue.Labels, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetLabels() *GetIssueIssueLabelsIssueLabelConnection { return v.Labels }

// GetParent returns GetIssueIssue.Parent, and is useful for accessing the field via an interface.
func (v *GetIssueIssue) GetParent() *GetIssueIssueParentIssue { return v.Parent }

// GetIssueIssueAssigneeUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type GetIssueIssueAssigneeUser struct {
	// The user's full name.
	Name string `json:"name"`
	// The user's email address.
	Email string `json:"email"`
}

// GetName returns GetIssueIssueAssigneeUser.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueAssigneeUser) GetName() string { return v.Name }

// GetEmail returns GetIssueIssueAssigneeUser.Email, and is useful for accessing the field via an interface.
func (v *GetIssueIssueAssigneeUser) GetEmail() string { return v.Email }

// GetIssueIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type GetIssueIssueLabelsIssueLabelConnection struct {
	Nodes []*GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns GetIssueIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetIssueIssueLabelsIssueLabelConnection) GetNodes() []*GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues.
type GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string { return v.Name }

// GetIssueIssueParentIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type GetIssueIssueParentIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
}

// GetIdentifier returns GetIssueIssueParentIssue.Identifier, and is useful for accessing the field via an interface.
func (v *GetIssueIssueParentIssue) GetIdentifier() string { return v.Identifier }

// GetTitle returns GetIssueIssueParentIssue.Title, and is useful for accessing the field via an interface.
func (v *GetIssueIssueParentIssue) GetTitle() string { return v.Title }

// GetIssueIssueProject includes the requested fields of the GraphQL type Project.
// The GraphQL type's documentation follows.
//
// A project.
type GetIssueIssueProject struct {
	// The project's name.
	Name string `json:"name"`
}

// GetName returns GetIssueIssueProject.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueProject) GetName() string { return v.Name }

// GetIssueIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team workflow.
type GetIssueIssueStateWorkflowState struct {
	// The state's name.
	Name string `json:"name"`
	// The type of the state. One of "triage", "backlog", "unstarted", "started", "completed", "canceled".
	Type string `json:"type"`
}

// GetName returns GetIssueIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueStateWorkflowState) GetName() string { return v.Name }

// GetType returns GetIssueIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *GetIssueIssueStateWorkflowState) GetType() string { return v.Type }

// GetIssueIssueTeam includes the requested fields of the GraphQL type Team.
// The GraphQL type's documentation follows.
//
// An organizational unit that contains issues.
type GetIssueIssueTeam struct {
	// The team's name.
	Name string `json:"name"`
	// The team's unique key. The key is used in URLs.
	Key string `json:"key"`
}

// GetName returns GetIssueIssueTeam.Name, and is useful for accessing the field via an interface.
func (v *GetIssueIssueTeam) GetName() string { return v.Name }

// GetKey returns GetIssueIssueTeam.Key, and is useful for accessing the field via an interface.
func (v *GetIssueIssueTeam) GetKey() string { return v.Key }

// GetIssueResponse is returned by GetIssue on success.
type GetIssueResponse struct {
	// One specific issue.
	Issue *GetIssueIssue `json:"issue"`
}

// GetIssue returns GetIssueResponse.Issue, and is useful for accessing the field via an interface.
func (v *GetIssueResponse) GetIssue() *GetIssueIssue { return v.Issue }

// GetUserByDisplayNameResponse is returned by GetUserByDisplayName on success.
type GetUserByDisplayNameResponse struct {
	// All users for the organization.
	Users *GetUserByDisplayNameUsersUserConnection `json:"users"`
}

// GetUsers returns GetUserByDisplayNameResponse.Users, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameResponse) GetUsers() *GetUserByDisplayNameUsersUserConnection {
	return v.Users
}

// GetUserByDisplayNameUsersUserConnection includes the requested fields of the GraphQL type UserConnection.
type GetUserByDisplayNameUsersUserConnection struct {
	Nodes []*GetUserByDisplayNameUsersUserConnectionNodesUser `json:"nodes"`
}

// GetNodes returns GetUserByDisplayNameUsersUserConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameUsersUserConnection) GetNodes() []*GetUserByDisplayNameUsersUserConnectionNodesUser {
	return v.Nodes
}

// GetUserByDisplayNameUsersUserConnectionNodesUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type GetUserByDisplayNameUsersUserConnectionNodesUser struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The user's full name.
	Name string `json:"name"`
	// The user's display (nick) name. Unique within each organization.
	DisplayName string `json:"displayName"`
	// The user's email address.
	Email string `json:"email"`
	// Whether the user account is active or disabled (suspended).
	Active bool `json:"active"`
	// Whether the user is an organization administrator.
	Admin bool `json:"admin"`
	// Whether the user is the currently authenticated user.
	IsMe bool `json:"isMe"`
}

// GetId returns GetUserByDisplayNameUsersUserConnectionNodesUser.Id, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameUsersUserConnectionNodesUser) GetId() string { return v.Id }

// GetName returns GetUserByDisplayNameUsersUserConnectionNodesUser.Name, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameUsersUserConnectionNodesUser) GetName() string { return v.Name }

// GetDisplayName returns GetUserByDisplayNameUsersUserConnectionNodesUser.DisplayName, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameUsersUserConnectionNodesUser) GetDisplayName() string {
	return v.DisplayName
}

// GetEmail returns GetUserByDisplayNameUsersUserConnectionNodesUser.Email, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameUsersUserConnectionNodesUser) GetEmail() string { return v.Email }

// GetActive returns GetUserByDisplayNameUsersUserConnectionNodesUser.Active, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameUsersUserConnectionNodesUser) GetActive() bool { return v.Active }

// GetAdmin returns GetUserByDisplayNameUsersUserConnectionNodesUser.Admin, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameUsersUserConnectionNodesUser) GetAdmin() bool { return v.Admin }

// GetIsMe returns GetUserByDisplayNameUsersUserConnectionNodesUser.IsMe, and is useful for accessing the field via an interface.
func (v *GetUserByDisplayNameUsersUserConnectionNodesUser) GetIsMe() bool { return v.IsMe }

// ListAllUserIssuesIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type ListAllUserIssuesIssuesIssueConnection struct {
	Nodes    []*ListAllUserIssuesIssuesIssueConnectionNodesIssue `json:"nodes"`
	PageInfo *ListAllUserIssuesIssuesIssueConnectionPageInfo     `json:"pageInfo"`
}

// GetNodes returns ListAllUserIssuesIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnection) GetNodes() []*ListAllUserIssuesIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GetPageInfo returns ListAllUserIssuesIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnection) GetPageInfo() *ListAllUserIssuesIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// ListAllUserIssuesIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type ListAllUserIssuesIssuesIssueConnectionNodesIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
	// The workflow state that the issue is associated with.
	State *ListAllUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState `json:"state"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
	Priority float64 `json:"priority"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
	// Labels associated with this issue.
	Labels *ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection `json:"labels"`
}

// GetId returns ListAllUserIssuesIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssue) GetId() string { return v.Id }

// GetIdentifier returns ListAllUserIssuesIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns ListAllUserIssuesIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssue) GetTitle() string { return v.Title }

// GetState returns ListAllUserIssuesIssuesIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssue) GetState() *ListAllUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetPriority returns ListAllUserIssuesIssuesIssueConnectionNodesIssue.Priority, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssue) GetPriority() float64 { return v.Priority }

// GetUpdatedAt returns ListAllUserIssuesIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssue) GetUpdatedAt() string { return v.UpdatedAt }

// GetLabels returns ListAllUserIssuesIssuesIssueConnectionNodesIssue.Labels, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssue) GetLabels() *ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection {
	return v.Labels
}

// ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection struct {
	Nodes []*ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection) GetNodes() []*ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues.
type ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string {
	return v.Name
}

// ListAllUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team workflow.
type ListAllUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState struct {
	// The state's name.
	Name string `json:"name"`
	// The type of the state. One of "triage", "backlog", "unstarted", "started", "completed", "canceled".
	Type string `json:"type"`
}

// GetName returns ListAllUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetType returns ListAllUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState) GetType() string {
	return v.Type
}

// ListAllUserIssuesIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ListAllUserIssuesIssuesIssueConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns ListAllUserIssuesIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionPageInfo) GetHasNextPage() bool { return v.HasNextPage }

// GetEndCursor returns ListAllUserIssuesIssuesIssueConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesIssuesIssueConnectionPageInfo) GetEndCursor() *string { return v.EndCursor }

// ListAllUserIssuesResponse is returned by ListAllUserIssues on success.
type ListAllUserIssuesResponse struct {
	// All issues.
	Issues *ListAllUserIssuesIssuesIssueConnection `json:"issues"`
}

// GetIssues returns ListAllUserIssuesResponse.Issues, and is useful for accessing the field via an interface.
func (v *ListAllUserIssuesResponse) GetIssues() *ListAllUserIssuesIssuesIssueConnection {
	return v.Issues
}

// ListMyActiveIssuesResponse is returned by ListMyActiveIssues on success.
type ListMyActiveIssuesResponse struct {
	// The currently authenticated user.
	Viewer *ListMyActiveIssuesViewerUser `json:"viewer"`
}

// GetViewer returns ListMyActiveIssuesResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesResponse) GetViewer() *ListMyActiveIssuesViewerUser { return v.Viewer }

// ListMyActiveIssuesViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ListMyActiveIssuesViewerUser struct {
	// Issues assigned to the user.
	AssignedIssues *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns ListMyActiveIssuesViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUser) GetAssignedIssues() *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection struct {
	Nodes    []*ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
	PageInfo *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo     `json:"pageInfo"`
}

// GetNodes returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection) GetNodes() []*ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GetPageInfo returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnection) GetPageInfo() *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
	// The workflow state that the issue is associated with.
	State *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState `json:"state"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
	Priority float64 `json:"priority"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
	// Labels associated with this issue.
	Labels *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection `json:"labels"`
}

// GetId returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetId() string {
	return v.Id
}

// GetIdentifier returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetState returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetState() *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetPriority returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Priority, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetPriority() float64 {
	return v.Priority
}

// GetUpdatedAt returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetLabels returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Labels, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetLabels() *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection {
	return v.Labels
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection struct {
	Nodes []*ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection) GetNodes() []*ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string {
	return v.Name
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team workflow.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState struct {
	// The state's name.
	Name string `json:"name"`
	// The type of the state. One of "triage", "backlog", "unstarted", "started", "completed", "canceled".
	Type string `json:"type"`
}

// GetName returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetType returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetType() string {
	return v.Type
}

// ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListMyActiveIssuesViewerUserAssignedIssuesIssueConnectionPageInfo) GetEndCursor() *string {
	return v.EndCursor
}

// ListMyAllIssuesResponse is returned by ListMyAllIssues on success.
type ListMyAllIssuesResponse struct {
	// The currently authenticated user.
	Viewer *ListMyAllIssuesViewerUser `json:"viewer"`
}

// GetViewer returns ListMyAllIssuesResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesResponse) GetViewer() *ListMyAllIssuesViewerUser { return v.Viewer }

// ListMyAllIssuesViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ListMyAllIssuesViewerUser struct {
	// Issues assigned to the user.
	AssignedIssues *ListMyAllIssuesViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns ListMyAllIssuesViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUser) GetAssignedIssues() *ListMyAllIssuesViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnection struct {
	Nodes    []*ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
	PageInfo *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo     `json:"pageInfo"`
}

// GetNodes returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnection) GetNodes() []*ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GetPageInfo returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnection) GetPageInfo() *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
	// The workflow state that the issue is associated with.
	State *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState `json:"state"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
	Priority float64 `json:"priority"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
	// Labels associated with this issue.
	Labels *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection `json:"labels"`
}

// GetId returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetId() string {
	return v.Id
}

// GetIdentifier returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetState returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetState() *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetPriority returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Priority, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetPriority() float64 {
	return v.Priority
}

// GetUpdatedAt returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetLabels returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Labels, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetLabels() *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection {
	return v.Labels
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection struct {
	Nodes []*ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection) GetNodes() []*ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string {
	return v.Name
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team workflow.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState struct {
	// The state's name.
	Name string `json:"name"`
	// The type of the state. One of "triage", "backlog", "unstarted", "started", "completed", "canceled".
	Type string `json:"type"`
}

// GetName returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetType returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetType() string {
	return v.Type
}

// ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListMyAllIssuesViewerUserAssignedIssuesIssueConnectionPageInfo) GetEndCursor() *string {
	return v.EndCursor
}

// ListUserIssuesIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type ListUserIssuesIssuesIssueConnection struct {
	Nodes    []*ListUserIssuesIssuesIssueConnectionNodesIssue `json:"nodes"`
	PageInfo *ListUserIssuesIssuesIssueConnectionPageInfo     `json:"pageInfo"`
}

// GetNodes returns ListUserIssuesIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnection) GetNodes() []*ListUserIssuesIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// GetPageInfo returns ListUserIssuesIssuesIssueConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnection) GetPageInfo() *ListUserIssuesIssuesIssueConnectionPageInfo {
	return v.PageInfo
}

// ListUserIssuesIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type ListUserIssuesIssuesIssueConnectionNodesIssue struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
	// The workflow state that the issue is associated with.
	State *ListUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState `json:"state"`
	// The priority of the issue. 0 = No priority, 1 = Urgent, 2 = High, 3 = Normal, 4 = Low.
	Priority float64 `json:"priority"`
	// The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't
	// been updated after creation.
	UpdatedAt string `json:"updatedAt"`
	// Labels associated with this issue.
	Labels *ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection `json:"labels"`
}

// GetId returns ListUserIssuesIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssue) GetId() string { return v.Id }

// GetIdentifier returns ListUserIssuesIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssue) GetIdentifier() string { return v.Identifier }

// GetTitle returns ListUserIssuesIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssue) GetTitle() string { return v.Title }

// GetState returns ListUserIssuesIssuesIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssue) GetState() *ListUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetPriority returns ListUserIssuesIssuesIssueConnectionNodesIssue.Priority, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssue) GetPriority() float64 { return v.Priority }

// GetUpdatedAt returns ListUserIssuesIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssue) GetUpdatedAt() string { return v.UpdatedAt }

// GetLabels returns ListUserIssuesIssuesIssueConnectionNodesIssue.Labels, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssue) GetLabels() *ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection {
	return v.Labels
}

// ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection includes the requested fields of the GraphQL type IssueLabelConnection.
type ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection struct {
	Nodes []*ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel `json:"nodes"`
}

// GetNodes returns ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnection) GetNodes() []*ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel {
	return v.Nodes
}

// ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel includes the requested fields of the GraphQL type IssueLabel.
// The GraphQL type's documentation follows.
//
// Labels that can be associated with issues.
type ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel struct {
	// The label's name.
	Name string `json:"name"`
}

// GetName returns ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel.Name, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssueLabelsIssueLabelConnectionNodesIssueLabel) GetName() string {
	return v.Name
}

// ListUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
// The GraphQL type's documentation follows.
//
// A state in a team workflow.
type ListUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState struct {
	// The state's name.
	Name string `json:"name"`
	// The type of the state. One of "triage", "backlog", "unstarted", "started", "completed", "canceled".
	Type string `json:"type"`
}

// GetName returns ListUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetType returns ListUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionNodesIssueStateWorkflowState) GetType() string {
	return v.Type
}

// ListUserIssuesIssuesIssueConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ListUserIssuesIssuesIssueConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns ListUserIssuesIssuesIssueConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionPageInfo) GetHasNextPage() bool { return v.HasNextPage }

// GetEndCursor returns ListUserIssuesIssuesIssueConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListUserIssuesIssuesIssueConnectionPageInfo) GetEndCursor() *string { return v.EndCursor }

// ListUserIssuesResponse is returned by ListUserIssues on success.
type ListUserIssuesResponse struct {
	// All issues.
	Issues *ListUserIssuesIssuesIssueConnection `json:"issues"`
}

// GetIssues returns ListUserIssuesResponse.Issues, and is useful for accessing the field via an interface.
func (v *ListUserIssuesResponse) GetIssues() *ListUserIssuesIssuesIssueConnection { return v.Issues }

// ListUsersResponse is returned by ListUsers on success.
type ListUsersResponse struct {
	// All users for the organization.
	Users *ListUsersUsersUserConnection `json:"users"`
}

// GetUsers returns ListUsersResponse.Users, and is useful for accessing the field via an interface.
func (v *ListUsersResponse) GetUsers() *ListUsersUsersUserConnection { return v.Users }

// ListUsersUsersUserConnection includes the requested fields of the GraphQL type UserConnection.
type ListUsersUsersUserConnection struct {
	Nodes    []*ListUsersUsersUserConnectionNodesUser `json:"nodes"`
	PageInfo *ListUsersUsersUserConnectionPageInfo    `json:"pageInfo"`
}

// GetNodes returns ListUsersUsersUserConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnection) GetNodes() []*ListUsersUsersUserConnectionNodesUser {
	return v.Nodes
}

// GetPageInfo returns ListUsersUsersUserConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnection) GetPageInfo() *ListUsersUsersUserConnectionPageInfo {
	return v.PageInfo
}

// ListUsersUsersUserConnectionNodesUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ListUsersUsersUserConnectionNodesUser struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The user's full name.
	Name string `json:"name"`
	// The user's display (nick) name. Unique within each organization.
	DisplayName string `json:"displayName"`
	// The user's email address.
	Email string `json:"email"`
	// Whether the user account is active or disabled (suspended).
	Active bool `json:"active"`
	// Whether the user is an organization administrator.
	Admin bool `json:"admin"`
	// Whether the user is the currently authenticated user.
	IsMe bool `json:"isMe"`
}

// GetId returns ListUsersUsersUserConnectionNodesUser.Id, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionNodesUser) GetId() string { return v.Id }

// GetName returns ListUsersUsersUserConnectionNodesUser.Name, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionNodesUser) GetName() string { return v.Name }

// GetDisplayName returns ListUsersUsersUserConnectionNodesUser.DisplayName, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionNodesUser) GetDisplayName() string { return v.DisplayName }

// GetEmail returns ListUsersUsersUserConnectionNodesUser.Email, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionNodesUser) GetEmail() string { return v.Email }

// GetActive returns ListUsersUsersUserConnectionNodesUser.Active, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionNodesUser) GetActive() bool { return v.Active }

// GetAdmin returns ListUsersUsersUserConnectionNodesUser.Admin, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionNodesUser) GetAdmin() bool { return v.Admin }

// GetIsMe returns ListUsersUsersUserConnectionNodesUser.IsMe, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionNodesUser) GetIsMe() bool { return v.IsMe }

// ListUsersUsersUserConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type ListUsersUsersUserConnectionPageInfo struct {
	// Indicates if there are more results when paginating forward.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor representing the last result in the paginated results.
	EndCursor *string `json:"endCursor"`
}

// GetHasNextPage returns ListUsersUsersUserConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionPageInfo) GetHasNextPage() bool { return v.HasNextPage }

// GetEndCursor returns ListUsersUsersUserConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListUsersUsersUserConnectionPageInfo) GetEndCursor() *string { return v.EndCursor }

// UserIssuesForCompletionIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type UserIssuesForCompletionIssuesIssueConnection struct {
	Nodes []*UserIssuesForCompletionIssuesIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns UserIssuesForCompletionIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *UserIssuesForCompletionIssuesIssueConnection) GetNodes() []*UserIssuesForCompletionIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// UserIssuesForCompletionIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An issue.
type UserIssuesForCompletionIssuesIssueConnectionNodesIssue struct {
	// Issue's human readable identifier (e.g. ENG-123).
	Identifier string `json:"identifier"`
	// The issue's title.
	Title string `json:"title"`
}

// GetIdentifier returns UserIssuesForCompletionIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *UserIssuesForCompletionIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns UserIssuesForCompletionIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *UserIssuesForCompletionIssuesIssueConnectionNodesIssue) GetTitle() string { return v.Title }

// UserIssuesForCompletionResponse is returned by UserIssuesForCompletion on success.
type UserIssuesForCompletionResponse struct {
	// All issues.
	Issues *UserIssuesForCompletionIssuesIssueConnection `json:"issues"`
}

// GetIssues returns UserIssuesForCompletionResponse.Issues, and is useful for accessing the field via an interface.
func (v *UserIssuesForCompletionResponse) GetIssues() *UserIssuesForCompletionIssuesIssueConnection {
	return v.Issues
}

// UsersForCompletionResponse is returned by UsersForCompletion on success.
type UsersForCompletionResponse struct {
	// All users for the organization.
	Users *UsersForCompletionUsersUserConnection `json:"users"`
}

// GetUsers returns UsersForCompletionResponse.Users, and is useful for accessing the field via an interface.
func (v *UsersForCompletionResponse) GetUsers() *UsersForCompletionUsersUserConnection {
	return v.Users
}

// UsersForCompletionUsersUserConnection includes the requested fields of the GraphQL type UserConnection.
type UsersForCompletionUsersUserConnection struct {
	Nodes []*UsersForCompletionUsersUserConnectionNodesUser `json:"nodes"`
}

// GetNodes returns UsersForCompletionUsersUserConnection.Nodes, and is useful for accessing the field via an interface.
func (v *UsersForCompletionUsersUserConnection) GetNodes() []*UsersForCompletionUsersUserConnectionNodesUser {
	return v.Nodes
}

// UsersForCompletionUsersUserConnectionNodesUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type UsersForCompletionUsersUserConnectionNodesUser struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The user's full name.
	Name string `json:"name"`
	// The user's display (nick) name. Unique within each organization.
	DisplayName string `json:"displayName"`
}

// GetId returns UsersForCompletionUsersUserConnectionNodesUser.Id, and is useful for accessing the field via an interface.
func (v *UsersForCompletionUsersUserConnectionNodesUser) GetId() string { return v.Id }

// GetName returns UsersForCompletionUsersUserConnectionNodesUser.Name, and is useful for accessing the field via an interface.
func (v *UsersForCompletionUsersUserConnectionNodesUser) GetName() string { return v.Name }

// GetDisplayName returns UsersForCompletionUsersUserConnectionNodesUser.DisplayName, and is useful for accessing the field via an interface.
func (v *UsersForCompletionUsersUserConnectionNodesUser) GetDisplayName() string {
	return v.DisplayName
}

// ViewerResponse is returned by Viewer on success.
type ViewerResponse struct {
	// The currently authenticated user.
	Viewer *ViewerViewerUser `json:"viewer"`
}

// GetViewer returns ViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *ViewerResponse) GetViewer() *ViewerViewerUser { return v.Viewer }

// ViewerViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user that has access to the the resources of an organization.
type ViewerViewerUser struct {
	// The unique identifier of the entity.
	Id string `json:"id"`
	// The user's full name.
	Name string `json:"name"`
	// The user's email address.
	Email string `json:"email"`
}

// GetId returns ViewerViewerUser.Id, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetId() string { return v.Id }

// GetName returns ViewerViewerUser.Name, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetName() string { return v.Name }

// GetEmail returns ViewerViewerUser.Email, and is useful for accessing the field via an interface.
func (v *ViewerViewerUser) GetEmail() string { return v.Email }

// __ActiveIssuesForCompletionInput is used internally by genqlient
type __ActiveIssuesForCompletionInput struct {
	First int `json:"first"`
}

// GetFirst returns __ActiveIssuesForCompletionInput.First, and is useful for accessing the field via an interface.
func (v *__ActiveIssuesForCompletionInput) GetFirst() int { return v.First }

// __GetIssueInput is used internally by genqlient
type __GetIssueInput struct {
	Id string `json:"id"`
}

// GetId returns __GetIssueInput.Id, and is useful for accessing the field via an interface.
func (v *__GetIssueInput) GetId() string { return v.Id }

// __GetUserByDisplayNameInput is used internally by genqlient
type __GetUserByDisplayNameInput struct {
	DisplayName string `json:"displayName"`
}

// GetDisplayName returns __GetUserByDisplayNameInput.DisplayName, and is useful for accessing the field via an interface.
func (v *__GetUserByDisplayNameInput) GetDisplayName() string { return v.DisplayName }

// __ListAllUserIssuesInput is used internally by genqlient
type __ListAllUserIssuesInput struct {
	First        int     `json:"first"`
	After        *string `json:"after"`
	AssigneeName string  `json:"assigneeName"`
}

// GetFirst returns __ListAllUserIssuesInput.First, and is useful for accessing the field via an interface.
func (v *__ListAllUserIssuesInput) GetFirst() int { return v.First }

// GetAfter returns __ListAllUserIssuesInput.After, and is useful for accessing the field via an interface.
func (v *__ListAllUserIssuesInput) GetAfter() *string { return v.After }

// GetAssigneeName returns __ListAllUserIssuesInput.AssigneeName, and is useful for accessing the field via an interface.
func (v *__ListAllUserIssuesInput) GetAssigneeName() string { return v.AssigneeName }

// __ListMyActiveIssuesInput is used internally by genqlient
type __ListMyActiveIssuesInput struct {
	First int     `json:"first"`
	After *string `json:"after"`
}

// GetFirst returns __ListMyActiveIssuesInput.First, and is useful for accessing the field via an interface.
func (v *__ListMyActiveIssuesInput) GetFirst() int { return v.First }

// GetAfter returns __ListMyActiveIssuesInput.After, and is useful for accessing the field via an interface.
func (v *__ListMyActiveIssuesInput) GetAfter() *string { return v.After }

// __ListMyAllIssuesInput is used internally by genqlient
type __ListMyAllIssuesInput struct {
	First int     `json:"first"`
	After *string `json:"after"`
}

// GetFirst returns __ListMyAllIssuesInput.First, and is useful for accessing the field via an interface.
func (v *__ListMyAllIssuesInput) GetFirst() int { return v.First }

// GetAfter returns __ListMyAllIssuesInput.After, and is useful for accessing the field via an interface.
func (v *__ListMyAllIssuesInput) GetAfter() *string { return v.After }

// __ListUserIssuesInput is used internally by genqlient
type __ListUserIssuesInput struct {
	First        int     `json:"first"`
	After        *string `json:"after"`
	AssigneeName string  `json:"assigneeName"`
}

// GetFirst returns __ListUserIssuesInput.First, and is useful for accessing the field via an interface.
func (v *__ListUserIssuesInput) GetFirst() int { return v.First }

// GetAfter returns __ListUserIssuesInput.After, and is useful for accessing the field via an interface.
func (v *__ListUserIssuesInput) GetAfter() *string { return v.After }

// GetAssigneeName returns __ListUserIssuesInput.AssigneeName, and is useful for accessing the field via an interface.
func (v *__ListUserIssuesInput) GetAssigneeName() string { return v.AssigneeName }

// __ListUsersInput is used internally by genqlient
type __ListUsersInput struct {
	First int     `json:"first"`
	After *string `json:"after"`
}

// GetFirst returns __ListUsersInput.First, and is useful for accessing the field via an interface.
func (v *__ListUsersInput) GetFirst() int { return v.First }

// GetAfter returns __ListUsersInput.After, and is useful for accessing the field via an interface.
func (v *__ListUsersInput) GetAfter() *string { return v.After }

// __UserIssuesForCompletionInput is used internally by genqlient
type __UserIssuesForCompletionInput struct {
	First        int    `json:"first"`
	AssigneeName string `json:"assigneeName"`
}

// GetFirst returns __UserIssuesForCompletionInput.First, and is useful for accessing the field via an interface.
func (v *__UserIssuesForCompletionInput) GetFirst() int { return v.First }

// GetAssigneeName returns __UserIssuesForCompletionInput.AssigneeName, and is useful for accessing the field via an interface.
func (v *__UserIssuesForCompletionInput) GetAssigneeName() string { return v.AssigneeName }

// __UsersForCompletionInput is used internally by genqlient
type __UsersForCompletionInput struct {
	First int `json:"first"`
}

// GetFirst returns __UsersForCompletionInput.First, and is useful for accessing the field via an interface.
func (v *__UsersForCompletionInput) GetFirst() int { return v.First }

// The query executed by ActiveIssuesForCompletion.
const ActiveIssuesForCompletion_Operation = `
query ActiveIssuesForCompletion ($first: Int!) {
	viewer {
		assignedIssues(first: $first, filter: {state:{type:{nin:["completed","canceled"]}}}) {
			nodes {
				identifier
				title
			}
		}
	}
}
`

func ActiveIssuesForCompletion(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
) (data_ *ActiveIssuesForCompletionResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ActiveIssuesForCompletion",
		Query:  ActiveIssuesForCompletion_Operation,
		Variables: &__ActiveIssuesForCompletionInput{
			First: first,
		},
	}

	data_ = &ActiveIssuesForCompletionResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetIssue.
const GetIssue_Operation = `
query GetIssue ($id: String!) {
	issue(id: $id) {
		id
		identifier
		title
		description
		url
		priority
		estimate
		dueDate
		createdAt
		updatedAt
		branchName
		state {
			name
			type
		}
		assignee {
			name
			email
		}
		team {
			name
			key
		}
		project {
			name
		}
		labels {
			nodes {
				name
			}
		}
		parent {
			identifier
			title
		}
	}
}
`

func GetIssue(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetIssueResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetIssue",
		Query:  GetIssue_Operation,
		Variables: &__GetIssueInput{
			Id: id,
		},
	}

	data_ = &GetIssueResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetUserByDisplayName.
const GetUserByDisplayName_Operation = `
query GetUserByDisplayName ($displayName: String!) {
	users(first: 1, filter: {displayName:{eqIgnoreCase:$displayName}}) {
		nodes {
			id
			name
			displayName
			email
			active
			admin
			isMe
		}
	}
}
`

func GetUserByDisplayName(
	ctx_ context.Context,
	client_ graphql.Client,
	displayName string,
) (data_ *GetUserByDisplayNameResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetUserByDisplayName",
		Query:  GetUserByDisplayName_Operation,
		Variables: &__GetUserByDisplayNameInput{
			DisplayName: displayName,
		},
	}

	data_ = &GetUserByDisplayNameResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListAllUserIssues.
const ListAllUserIssues_Operation = `
query ListAllUserIssues ($first: Int!, $after: String, $assigneeName: String!) {
	issues(first: $first, after: $after, filter: {assignee:{displayName:{eqIgnoreCase:$assigneeName}}}) {
		nodes {
			id
			identifier
			title
			state {
				name
				type
			}
			priority
			updatedAt
			labels {
				nodes {
					name
				}
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func ListAllUserIssues(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after *string,
	assigneeName string,
) (data_ *ListAllUserIssuesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListAllUserIssues",
		Query:  ListAllUserIssues_Operation,
		Variables: &__ListAllUserIssuesInput{
			First:        first,
			After:        after,
			AssigneeName: assigneeName,
		},
	}

	data_ = &ListAllUserIssuesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListMyActiveIssues.
const ListMyActiveIssues_Operation = `
query ListMyActiveIssues ($first: Int!, $after: String) {
	viewer {
		assignedIssues(first: $first, after: $after, filter: {state:{type:{nin:["completed","canceled"]}}}) {
			nodes {
				id
				identifier
				title
				state {
					name
					type
				}
				priority
				updatedAt
				labels {
					nodes {
						name
					}
				}
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}
`

func ListMyActiveIssues(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after *string,
) (data_ *ListMyActiveIssuesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListMyActiveIssues",
		Query:  ListMyActiveIssues_Operation,
		Variables: &__ListMyActiveIssuesInput{
			First: first,
			After: after,
		},
	}

	data_ = &ListMyActiveIssuesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListMyAllIssues.
const ListMyAllIssues_Operation = `
query ListMyAllIssues ($first: Int!, $after: String) {
	viewer {
		assignedIssues(first: $first, after: $after) {
			nodes {
				id
				identifier
				title
				state {
					name
					type
				}
				priority
				updatedAt
				labels {
					nodes {
						name
					}
				}
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}
`

func ListMyAllIssues(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after *string,
) (data_ *ListMyAllIssuesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListMyAllIssues",
		Query:  ListMyAllIssues_Operation,
		Variables: &__ListMyAllIssuesInput{
			First: first,
			After: after,
		},
	}

	data_ = &ListMyAllIssuesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListUserIssues.
const ListUserIssues_Operation = `
query ListUserIssues ($first: Int!, $after: String, $assigneeName: String!) {
	issues(first: $first, after: $after, filter: {assignee:{displayName:{eqIgnoreCase:$assigneeName}},state:{type:{nin:["completed","canceled"]}}}) {
		nodes {
			id
			identifier
			title
			state {
				name
				type
			}
			priority
			updatedAt
			labels {
				nodes {
					name
				}
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func ListUserIssues(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after *string,
	assigneeName string,
) (data_ *ListUserIssuesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListUserIssues",
		Query:  ListUserIssues_Operation,
		Variables: &__ListUserIssuesInput{
			First:        first,
			After:        after,
			AssigneeName: assigneeName,
		},
	}

	data_ = &ListUserIssuesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListUsers.
const ListUsers_Operation = `
query ListUsers ($first: Int!, $after: String) {
	users(first: $first, after: $after) {
		nodes {
			id
			name
			displayName
			email
			active
			admin
			isMe
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func ListUsers(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after *string,
) (data_ *ListUsersResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListUsers",
		Query:  ListUsers_Operation,
		Variables: &__ListUsersInput{
			First: first,
			After: after,
		},
	}

	data_ = &ListUsersResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by UserIssuesForCompletion.
const UserIssuesForCompletion_Operation = `
query UserIssuesForCompletion ($first: Int!, $assigneeName: String!) {
	issues(first: $first, filter: {assignee:{displayName:{eqIgnoreCase:$assigneeName}},state:{type:{nin:["completed","canceled"]}}}) {
		nodes {
			identifier
			title
		}
	}
}
`

func UserIssuesForCompletion(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	assigneeName string,
) (data_ *UserIssuesForCompletionResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UserIssuesForCompletion",
		Query:  UserIssuesForCompletion_Operation,
		Variables: &__UserIssuesForCompletionInput{
			First:        first,
			AssigneeName: assigneeName,
		},
	}

	data_ = &UserIssuesForCompletionResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by UsersForCompletion.
const UsersForCompletion_Operation = `
query UsersForCompletion ($first: Int!) {
	users(first: $first) {
		nodes {
			id
			name
			displayName
		}
	}
}
`

func UsersForCompletion(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
) (data_ *UsersForCompletionResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UsersForCompletion",
		Query:  UsersForCompletion_Operation,
		Variables: &__UsersForCompletionInput{
			First: first,
		},
	}

	data_ = &UsersForCompletionResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Viewer.
const Viewer_Operation = `
query Viewer {
	viewer {
		id
		name
		email
	}
}
`

func Viewer(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ViewerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Viewer",
		Query:  Viewer_Operation,
	}

	data_ = &ViewerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
